In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr.shape

(4,)

In [6]:
arr2 = arr.reshape(4,1)
arr2

array([[1],
       [2],
       [3],
       [4]])

In [7]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [8]:
np.arange(0,10,3).reshape(4,1)

array([[0],
       [3],
       [6],
       [9]])

In [10]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [11]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
## Attributes of Numpy Array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)  # Output: (2, 3)
print("Number of dimensions:", arr.ndim)  # Output: 2
print("Size (number of elements):", arr.size)  # Output: 6
print("Data type:", arr.dtype)  # Output: int32 (may vary based on platform)
print("Item size (in bytes):", arr.itemsize)  # Output: 8 (may vary based on platform)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [20]:
arr1 = np.random.randint(1,10,size=[3,3])
arr2 = np.random.randint(1,10,size=[3,3])
print(arr1,arr2,sep="\n\n")

[[4 8 5]
 [9 1 4]
 [2 2 1]]

[[4 5 1]
 [6 7 4]
 [3 5 5]]


In [22]:
### Element Wise addition
print("Addition \n", arr1+arr2)

## Element Wise Substraction
print("Substraction \n", arr1-arr2)

# Element-wise multiplication
print("Multiplication \n", arr1 * arr2)

# Element-wise division
print("Division \n", arr1 / arr2)

Addition 
 [[ 8 13  6]
 [15  8  8]
 [ 5  7  6]]
Substraction 
 [[ 0  3  4]
 [ 3 -6  0]
 [-1 -3 -4]]
Multiplication 
 [[16 40  5]
 [54  7 16]
 [ 6 10  5]]
Division 
 [[1.         1.6        5.        ]
 [1.5        0.14285714 1.        ]
 [0.66666667 0.4        0.2       ]]


In [25]:
print(arr)

## square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sine
print(np.sin(arr))

## natural log
print(np.log(arr))

[[1 2 3]
 [4 5 6]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]
[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]


In [33]:
arr = np.random.randint(1,10,size=[7,7])
arr

array([[9, 7, 5, 7, 7, 7, 6],
       [1, 7, 3, 8, 6, 6, 5],
       [5, 9, 9, 1, 9, 4, 7],
       [5, 5, 3, 8, 3, 6, 1],
       [7, 9, 6, 8, 7, 8, 4],
       [2, 5, 2, 3, 8, 6, 7],
       [3, 4, 7, 9, 3, 1, 5]], dtype=int32)

In [35]:
# 5 1 
# 7 3

print(arr[2:4,4:6])



[[9 4]
 [3 6]]


In [36]:
arr[2:] = 99
arr

array([[ 9,  7,  5,  7,  7,  7,  6],
       [ 1,  7,  3,  8,  6,  6,  5],
       [99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99]], dtype=int32)

In [37]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25
