### Prac

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr.shape

(4,)

In [5]:
arr2 = arr.reshape(4,1)
arr2

array([[1],
       [2],
       [3],
       [4]])

In [6]:
arr2.shape

(4, 1)

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [13]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

In [14]:
arr.shape

(2, 3)

In [15]:
arr.ndim

2

In [16]:
arr.size

6

In [17]:
arr.itemsize

8

In [18]:
arr.dtype

dtype('int64')

In [19]:
arr1 = np.random.randint(1,10,size=[3,3])
arr2 = np.random.randint(1,10,size=[3,3])

print(arr1)
print(arr2)

[[6 3 5]
 [6 7 9]
 [1 8 3]]
[[9 7 1]
 [2 8 7]
 [8 7 2]]


In [20]:
arr1 + arr2

array([[15, 10,  6],
       [ 8, 15, 16],
       [ 9, 15,  5]], dtype=int32)

In [21]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [22]:
np.sin(arr)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [23]:
np.exp(arr)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])